### ISSUE TITLE
Any plans to make this a python module in pypi?

### ISSUE THREAD

**Issue by categulario** [J-Rios/multicolorcaptcha#2]
If this was a python module it could be easily installed via `pip` and that would simplify setup of `joincaptchabot` also. I can provide a pull request that helps make this a pyhton module since I have some experience with them. However the change implies modifying how this module gets installed and the directory structure.

What do you think?

**Comment by J-Rios** [comment]
Hi, totally agree, it has not been done because I don't have experience on how to do it. PR for this will be accepted :)

**Comment by J-Rios** [comment]
Done, thanks to your PR, multicolorcaptcha is now avaiblable in pypi:
[https://pypi.org/project/multicolorcaptcha](https://pypi.org/project/multicolorcaptcha)

P.D. Also, updated JoinCaptchaBot to use it from installed package instead submodule.

Kind Regards :)

**Comment by categulario** [comment]
Yay! That's amazing news!
