### ISSUE TITLE
How to generate a 640*160 image instead of 640*320

### ISSUE THREAD

**Issue by jet10000** [J-Rios/multicolorcaptcha#8]
![image](https://user-images.githubusercontent.com/2258120/145056814-0ed27f75-66d1-4122-805b-557289d19f50.png)

Do I still need to crop the image again?

**Comment by WardPearce** [comment]
Isn't very well documented, but both [gen_captcha_image](https://github.com/J-Rios/multicolorcaptcha/blob/development/multicolorcaptcha/_generator.py#L512) & [gen_math_captcha_image](https://github.com/J-Rios/multicolorcaptcha/blob/development/multicolorcaptcha/_generator.py#L614) have a parameter called `margin` what will disable the captcha black borders

**Comment by jet10000** [comment]
Thanks
